declare const N: any
declare const C: any
declare const FLARE: any
declare const FLARE_C: any
declare const PICKER: any
declare const PICKER_C: any
declare const PHOTO: any
declare const PHOTO_C: any
declare const LOTTIE: any
declare const LOTTIE_C: any
declare const REFRESH: any
declare const REFRESH_C: any
declare var OctoAppBundleId: any
declare const kIsWeb: boolean
declare const kHtmlMode: boolean