use_frameworks!

platform :ios, '10.0'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
  config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
  config.build_settings['VALID_ARCHS'] = 'arm64 arm64e armv7 armv7s x86_64 i386'
  config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end

target 'demo-ios' do
  pod 'SSZipArchive'
end
